version: '3.8'

services:
  # PHP API Backend
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=development
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mongodb
    networks:
      - my-shop-network

  # MongoDB Database
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: my_shop
    volumes:
      - mongodb_data:/data/db
      - ./backend/docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - my-shop-network

  # MongoDB Express (Web-based MongoDB admin interface)
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_DATABASE: my_shop
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - my-shop-network

  # React Frontend (Development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    networks:
      - my-shop-network

volumes:
  mongodb_data:

networks:
  my-shop-network:
    driver: bridge
